/**
 * API client for Sana AI Hub backend.
 * Handles all HTTP communication with the FastAPI server.
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

export interface RunStatus {
  run_id: string;
  phase: string;
  status: string;
  error: string | null;
  output_dir: string | null;
}

export interface ImagesList {
  images: string[];
  count: number;
}

export interface ReportData {
  content: string;
  filename: string;
}

export interface ColumnStats {
  column: string;
  standard_deviation: number;
  max: number;
  min: number;
  variance: number;
  range: number;
  median: number;
  mode: number | null;
}

export interface StatsResponse {
  run_id: string;
  rows: number;
  columns: number;
  numeric_columns: number;
  stats: ColumnStats[];
}

export interface CustomChartResponse {
  run_id: string;
  filename: string;
  chart_type: string;
  columns_used: string[];
  instruction: string;
}

export class APIError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "APIError";
  }
}

async function handleResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const text = await response.text();
    throw new APIError(response.status, text || `HTTP ${response.status}`);
  }
  return response.json() as Promise<T>;
}

/**
 * Start a new pipeline run.
 * @param url URL to process
 * @returns The run_id to track the pipeline
 */
export async function startPipeline(url: string): Promise<string> {
  const response = await fetch(`${API_BASE_URL}/run/json`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ source: url }),
  });

  const data = await handleResponse<RunStatus>(response);
  return data.run_id;
}

/**
 * Get the current status of a pipeline run.
 * @param runId The run_id to check
 * @returns Current status, phase, and any errors
 */
export async function checkStatus(runId: string): Promise<RunStatus> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}`);
  return handleResponse<RunStatus>(response);
}

/**
 * Download the cleaned CSV data for a completed pipeline.
 * @param runId The run_id
 * @returns Blob containing the CSV file
 */
export async function downloadCSV(runId: string): Promise<Blob> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}/data.csv`);
  if (!response.ok) {
    throw new APIError(response.status, "Failed to download CSV");
  }
  return response.blob();
}

/**
 * List all PNG images generated by Phase 3.
 * @param runId The run_id
 * @returns List of image filenames
 */
export async function fetchImagesList(runId: string): Promise<ImagesList> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}/images`);
  return handleResponse<ImagesList>(response);
}

/**
 * Get a specific PNG image from Phase 3.
 * @param runId The run_id
 * @param filename The image filename
 * @returns Image blob
 */
export async function fetchImageBlob(
  runId: string,
  filename: string,
): Promise<Blob> {
  const response = await fetch(
    `${API_BASE_URL}/runs/${runId}/images/${encodeURIComponent(filename)}`,
  );
  if (!response.ok) {
    throw new APIError(response.status, `Failed to fetch image: ${filename}`);
  }
  return response.blob();
}

/**
 * Get image URL for direct display in HTML.
 * @param runId The run_id
 * @param filename The image filename
 * @returns Direct image URL
 */
export function getImageURL(runId: string, filename: string): string {
  return `${API_BASE_URL}/runs/${runId}/images/${encodeURIComponent(filename)}`;
}

/**
 * Fetch the final markdown report (validation_report.md preferred, analysis_report.md fallback).
 * @param runId The run_id
 * @returns Markdown content
 */
export async function fetchReport(runId: string): Promise<ReportData> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}/report`);
  return handleResponse<ReportData>(response);
}

/**
 * Fetch descriptive statistics for cleaned numeric columns.
 */
export async function fetchSummaryStats(runId: string): Promise<StatsResponse> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}/stats`);
  return handleResponse<StatsResponse>(response);
}

/**
 * Generate custom chart based on a natural-language visualization instruction.
 */
export async function generateCustomChart(
  runId: string,
  instruction: string,
): Promise<CustomChartResponse> {
  const response = await fetch(`${API_BASE_URL}/runs/${runId}/charts/custom`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ instruction }),
  });
  return handleResponse<CustomChartResponse>(response);
}

/**
 * Parse CSV string into array of objects.
 * @param csvText CSV content
 * @returns Array of objects with column headers as keys
 */
export function parseCSV(csvText: string): Record<string, string>[] {
  const lines = csvText.trim().split("\n");
  if (lines.length < 1) return [];

  const headers = lines[0].split(",").map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const values = line.split(",").map((v) => v.trim());
    const obj: Record<string, string> = {};
    headers.forEach((header, i) => {
      obj[header] = values[i] || "";
    });
    return obj;
  });
}

/**
 * Health check endpoint.
 * @returns true if API is responding
 */
export async function healthCheck(): Promise<boolean> {
  try {
    const response = await fetch(`${API_BASE_URL}/health`);
    return response.ok;
  } catch {
    return false;
  }
}
